#!/bin/bash

#$ -P bf528
#$ -cwd

source /etc/bashrc

zcat /projectnb2/bf528/project_4_scrnaseq/fastq/SRR3879604/SRR3879604_1_bc.fastq.gz | awk 'NR%4==2' | cut -c -19 | sort | uniq -c | sort > SRR3879604_bc1.txt

zcat /projectnb2/bf528/project_4_scrnaseq/fastq/SRR3879605/SRR3879605_1_bc.fastq.gz | awk 'NR%4==2' | cut -c -19 | sort | uniq -c | sort > SRR3879605_bc1.txt

zcat /projectnb2/bf528/project_4_scrnaseq/fastq/SRR3879606/SRR3879606_1_bc.fastq.gz | awk 'NR%4==2' | cut -c -19 | sort | uniq -c | sort > SRR3879606_bc1.txt
